# Generated by Django 5.1.4 on 2025-01-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conatcts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefon',
            name='mobile',
            field=models.CharField(default=32, max_length=25),
            preserve_default=False,
        ),
    ]
